package net.unifar.mydiary.presentation.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val DarkBlue = Color(0xFF09072e)
val LightRed = Color(0xFFFF8A80)
val LightBlue = Color(0xFF8ae9ff)

val SundayRed = Color(0xFFff4238)
val SaturdayBlue = Color(0xFF29b9f2)

data class ExtraColors(
    val weekDayText: Color,
    val saturdayText: Color,
    val sundayText: Color,
    val holidayText: Color,
)


val primaryLight = Color(0xFF1C2E3B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF324452)
val onPrimaryContainerLight = Color(0xFF9EB1C2)
val secondaryLight = Color(0xFF585F66)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDAE0E8)
val onSecondaryContainerLight = Color(0xFF5D636A)
val tertiaryLight = Color(0xFF362639)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF4D3C50)
val onTertiaryContainerLight = Color(0xFFBEA7BF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBF9FA)
val onBackgroundLight = Color(0xFF1B1C1D)
val surfaceLight = Color(0xFFFBF9FA)
val onSurfaceLight = Color(0xFF1B1C1D)
val surfaceVariantLight = Color(0xFFDFE3E8)
val onSurfaceVariantLight = Color(0xFF43474B)
val outlineLight = Color(0xFF73777C)
val outlineVariantLight = Color(0xFFC3C7CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303031)
val inverseOnSurfaceLight = Color(0xFFF2F0F1)
val inversePrimaryLight = Color(0xFFB6C9DA)
val surfaceDimLight = Color(0xFFDBD9DA)
val surfaceBrightLight = Color(0xFFFBF9FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F3F4)
val surfaceContainerLight = Color(0xFFEFEDEE)
val surfaceContainerHighLight = Color(0xFFE9E8E9)
val surfaceContainerHighestLight = Color(0xFFE4E2E3)

val primaryLightMediumContrast = Color(0xFF1C2E3B)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF324452)
val onPrimaryContainerLightMediumContrast = Color(0xFFC7DBEC)
val secondaryLightMediumContrast = Color(0xFF30373D)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF676E74)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF362639)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4D3C50)
val onTertiaryContainerLightMediumContrast = Color(0xFFE9D0EA)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFBF9FA)
val onBackgroundLightMediumContrast = Color(0xFF1B1C1D)
val surfaceLightMediumContrast = Color(0xFFFBF9FA)
val onSurfaceLightMediumContrast = Color(0xFF101112)
val surfaceVariantLightMediumContrast = Color(0xFFDFE3E8)
val onSurfaceVariantLightMediumContrast = Color(0xFF32373B)
val outlineLightMediumContrast = Color(0xFF4F5357)
val outlineVariantLightMediumContrast = Color(0xFF696D72)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303031)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF2F0F1)
val inversePrimaryLightMediumContrast = Color(0xFFB6C9DA)
val surfaceDimLightMediumContrast = Color(0xFFC7C6C7)
val surfaceBrightLightMediumContrast = Color(0xFFFBF9FA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF5F3F4)
val surfaceContainerLightMediumContrast = Color(0xFFE9E8E9)
val surfaceContainerHighLightMediumContrast = Color(0xFFDEDCDD)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD3D1D2)

val primaryLightHighContrast = Color(0xFF1C2E3B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF324452)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF262D33)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF434A50)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF362639)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF4D3C50)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFBF9FA)
val onBackgroundLightHighContrast = Color(0xFF1B1C1D)
val surfaceLightHighContrast = Color(0xFFFBF9FA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE3E8)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF282D31)
val outlineVariantLightHighContrast = Color(0xFF454A4E)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303031)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFB6C9DA)
val surfaceDimLightHighContrast = Color(0xFFB9B8B9)
val surfaceBrightLightHighContrast = Color(0xFFFBF9FA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF2F0F1)
val surfaceContainerLightHighContrast = Color(0xFFE4E2E3)
val surfaceContainerHighLightHighContrast = Color(0xFFD5D4D5)
val surfaceContainerHighestLightHighContrast = Color(0xFFC7C6C7)

val primaryDark = Color(0xFFB6C9DA)
val onPrimaryDark = Color(0xFF203240)
val primaryContainerDark = Color(0xFF324452)
val onPrimaryContainerDark = Color(0xFF9EB1C2)
val secondaryDark = Color(0xFFC1C7CF)
val onSecondaryDark = Color(0xFF2A3137)
val secondaryContainerDark = Color(0xFF434A50)
val onSecondaryContainerDark = Color(0xFFB2B9C0)
val tertiaryDark = Color(0xFFD7BFD8)
val onTertiaryDark = Color(0xFF3B2B3E)
val tertiaryContainerDark = Color(0xFF4D3C50)
val onTertiaryContainerDark = Color(0xFFBEA7BF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131314)
val onBackgroundDark = Color(0xFFE4E2E3)
val surfaceDark = Color(0xFF131314)
val onSurfaceDark = Color(0xFFE4E2E3)
val surfaceVariantDark = Color(0xFF43474B)
val onSurfaceVariantDark = Color(0xFFC3C7CC)
val outlineDark = Color(0xFF8D9196)
val outlineVariantDark = Color(0xFF43474B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E2E3)
val inverseOnSurfaceDark = Color(0xFF303031)
val inversePrimaryDark = Color(0xFF4E616F)
val surfaceDimDark = Color(0xFF131314)
val surfaceBrightDark = Color(0xFF39393A)
val surfaceContainerLowestDark = Color(0xFF0D0E0F)
val surfaceContainerLowDark = Color(0xFF1B1C1D)
val surfaceContainerDark = Color(0xFF1F2021)
val surfaceContainerHighDark = Color(0xFF292A2B)
val surfaceContainerHighestDark = Color(0xFF343536)

val primaryDarkMediumContrast = Color(0xFFCBDFF0)
val onPrimaryDarkMediumContrast = Color(0xFF152835)
val primaryContainerDarkMediumContrast = Color(0xFF8093A3)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD6DDE5)
val onSecondaryDarkMediumContrast = Color(0xFF20262C)
val secondaryContainerDarkMediumContrast = Color(0xFF8B9198)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFEDD5EE)
val onTertiaryDarkMediumContrast = Color(0xFF2F2033)
val tertiaryContainerDarkMediumContrast = Color(0xFF9F8AA1)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF131314)
val onBackgroundDarkMediumContrast = Color(0xFFE4E2E3)
val surfaceDarkMediumContrast = Color(0xFF131314)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF43474B)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD9DCE2)
val outlineDarkMediumContrast = Color(0xFFAFB2B7)
val outlineVariantDarkMediumContrast = Color(0xFF8D9195)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE4E2E3)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF292A2B)
val inversePrimaryDarkMediumContrast = Color(0xFF384A58)
val surfaceDimDarkMediumContrast = Color(0xFF131314)
val surfaceBrightDarkMediumContrast = Color(0xFF444445)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070708)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1E1F)
val surfaceContainerDarkMediumContrast = Color(0xFF272829)
val surfaceContainerHighDarkMediumContrast = Color(0xFF323234)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3E3F)

val primaryDarkHighContrast = Color(0xFFE4F2FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB2C5D6)
val onPrimaryContainerDarkHighContrast = Color(0xFF000D17)
val secondaryDarkHighContrast = Color(0xFFEAF1F8)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBDC3CB)
val onSecondaryContainerDarkHighContrast = Color(0xFF060C11)
val tertiaryDarkHighContrast = Color(0xFFFFE9FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD3BBD4)
val onTertiaryContainerDarkHighContrast = Color(0xFF130617)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF131314)
val onBackgroundDarkHighContrast = Color(0xFFE4E2E3)
val surfaceDarkHighContrast = Color(0xFF131314)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF43474B)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEDF0F5)
val outlineVariantDarkHighContrast = Color(0xFFBFC3C8)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE4E2E3)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF384A58)
val surfaceDimDarkHighContrast = Color(0xFF131314)
val surfaceBrightDarkHighContrast = Color(0xFF505051)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F2021)
val surfaceContainerDarkHighContrast = Color(0xFF303031)
val surfaceContainerHighDarkHighContrast = Color(0xFF3B3B3C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF464748)












